### ISSUE TITLE
Use with getpage

### ISSUE THREAD

**Issue by funkyduke** [craftsmancoding/assetmanager#40]
How do I use this with getpage for pagination? This doesn't work:
 [[!getPage
&element=`getPageAssets`
&innerTpl=`AssetsTpl`
&is_image=`1`
&limit=`10`
 &pageVarKey=`page`
&pageNavVar=`page.nav`
&totalVar=`total`
 ]] 
[[+page.nav]]

I get the limit of 10 images, but no pagination.

**Comment by fireproofsocks** [comment]
Sorry, it's incompatible with getPage.
