### ISSUE TITLE
version 1.1.1 breaking grids display elsewhere in modx

### ISSUE THREAD

**Issue by digitalpenguin** [craftsmancoding/assetmanager#43]
Just updated to the new Asset Manager 1.1.1!

Unfortunately it appears to break the CSS (i'm guessing) of any grids in the modx manager. If I uninstall Asset Manager the grids return to normal. I'll attach a screenshot of each. MODX 2.3.3

This is my system settings with Asset Manager installed
![bad](https://cloud.githubusercontent.com/assets/5160368/6408828/298229a4-be96-11e4-8b5f-ce1b59337062.png)

This is the same thing after uninstalling Asset Manager again
![good](https://cloud.githubusercontent.com/assets/5160368/6408836/47bbf0bc-be96-11e4-8e71-5522eee18a34.png)

**Comment by dadaniels** [comment]
The conflicts is because of the classy table class that which was used on one of the CMPs. I updated the class name it made it like classy-assetmgr to avoid css conflicts.
