### ISSUE TITLE
A couple issues

### ISSUE THREAD

**Issue by robcarey** [craftsmancoding/assetmanager#46]
I have a couple issues - 

#1 I get an alert error on adding a new asset:

Something went wrong. Please check the Asset Manager Setting Page and See if the image meet the max upload size

However - setting appear to be fine. 2MB minimum set - only testing with a couple hundred kb files.

Next - despite the error message, the images are uploaded (verified over FTP) and thumbnails created - however - I can't do much with them, such as delete or drag to trash.  On hover I get an error "Invalid JSON response from server" on top of the thumbnail.

Any tips would be appreciated - this add-on looks promising!

**Comment by fireproofsocks** [comment]
What version of the extra are you using?  And can you clarify exactly how you're adding assets?  There are several ways to do this, each of which executes a different segment of code, so without specifics I can't narrow down the likely cause.

Also, check your logs -- anything in there?  Some environments have more restrictive permissions, so you can get errors even if the file is there.  

What are the file names?  Can you attach one of the problematic images?  I want to rule out corrupted files or errors with utf8/unicode.

This is a promising bug report... just needs a few more details ;)

**Comment by robcarey** [comment]
No issues showing in the apache error log.  Using Asset Manager 1.1.1-pl from the ModX package manager repo.  A clean recent install of Modx 2.3.3-pl on Ubuntu 14.04

PPH 5.5.9 / Apache 2.4.7

Nothing special about the images - had issues with several (all actually) from different creation sources.  A couple examples attached, as well as a screenshot of the error in the manager.

Assets were added both by dragging/dropping and using the select button.  Same issue on both.  Using current version of Chrome browser.

Worth noting - on reloading the page in the manager, there are no assets listed after this.  They still reside on the server, but it seems their DB records have not been stored (?)

![no-picture](https://cloud.githubusercontent.com/assets/3990764/6486090/7da6a726-c256-11e4-8ff2-548fc527643d.jpg)

![error-1](https://cloud.githubusercontent.com/assets/3990764/6486096/8b027602-c256-11e4-84e8-9a1ff539ebbe.JPG)

**Comment by robcarey** [comment]
Also - here's the javascript error log on the issue - I removed the binary data (file contents) from this error for clarity, but it's otherwise untouched:

[Dropzone Error] Fileaccepted: trueheight: 56lastModified: 1422631960000lastModifiedDate: Fri Jan 30 2015 10:32:40 GMT-0500 (Eastern Standard Time)__proto__: Invalid Datename: "217140-112x56-Cricket-150x75.png"previewElement: div.dz-preview.dz-processing.dz-image-preview.dz-erroraccessKey: ""align: ""attributes: NamedNodeMapbaseURI: "https://salestoolsdev.sandvine.com/sv-manager/?a=resource/update&id=1"childElementCount: 5childNodes: NodeList[10]children: HTMLCollection[5]classList: DOMTokenList[4]className: "dz-preview dz-processing dz-image-preview dz-error"clientHeight: 144clientLeft: 1clientTop: 1clientWidth: 122contentEditable: "inherit"dataset: DOMStringMapdir: ""draggable: falsefirstChild: textfirstElementChild: div.dz-detailshidden: falseid: ""innerHTML: "  <div class="dz-details">    <div class="dz-filename"><span data-dz-name="">217140-112x56-Cricket-150x75.png</span></div>    <div class="dz-size" data-dz-size=""><strong>3</strong> KB</div>    <img data-dz-thumbnail="" alt="217140-112x56-Cricket-150x75.png" src="[FILE DATA REMOVED FOR CLARITY] ">  </div>  <div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress="" style="width: 100%;"></span></div>  <div class="dz-success-mark"><span>✔</span></div>  <div class="dz-error-mark"><span>✘</span></div>  <div class="dz-error-message"><span data-dz-errormessage="">Invalid JSON response from server.</span></div>"innerText: "217140-112x56-Cricket-150x75.png↵3 KB✘"isContentEditable: falselang: ""lastChild: div.dz-error-messagelastElementChild: div.dz-error-messagelocalName: "div"namespaceURI: "http://www.w3.org/1999/xhtml"nextElementSibling: nullnextSibling: nullnodeName: "DIV"nodeType: 1nodeValue: nulloffsetHeight: 146offsetLeft: 32offsetParent: div#ext-gen269.x-panel-body.tab-panel-wrapper.x-panel-body-noheaderoffsetTop: 127offsetWidth: 124onabort: nullonautocomplete: nullonautocompleteerror: nullonbeforecopy: nullonbeforecut: nullonbeforepaste: nullonblur: nulloncancel: nulloncanplay: nulloncanplaythrough: nullonchange: nullonclick: nullonclose: nulloncontextmenu: nulloncopy: nulloncuechange: nulloncut: nullondblclick: nullondrag: nullondragend: nullondragenter: nullondragleave: nullondragover: nullondragstart: nullondrop: nullondurationchange: nullonemptied: nullonended: nullonerror: nullonfocus: nulloninput: nulloninvalid: nullonkeydown: nullonkeypress: nullonkeyup: nullonload: nullonloadeddata: nullonloadedmetadata: nullonloadstart: nullonmousedown: nullonmouseenter: nullonmouseleave: nullonmousemove: nullonmouseout: nullonmouseover: nullonmouseup: nullonmousewheel: nullonpaste: nullonpause: nullonplay: nullonplaying: nullonprogress: nullonratechange: nullonreset: nullonresize: nullonscroll: nullonsearch: nullonseeked: nullonseeking: nullonselect: nullonselectstart: nullonshow: nullonstalled: nullonsubmit: nullonsuspend: nullontimeupdate: nullontoggle: nullonvolumechange: nullonwaiting: nullonwebkitfullscreenchange: nullonwebkitfullscreenerror: nullonwheel: nullouterHTML: "<div class="dz-preview dz-processing dz-image-preview dz-error">  <div class="dz-details">    <div class="dz-filename"><span data-dz-name="">217140-112x56-Cricket-150x75.png</span></div>    <div class="dz-size" data-dz-size=""><strong>3</strong> KB</div>    <img data-dz-thumbnail="" alt="217140-112x56-Cricket-150x75.png" src="[FILE DATA REMOVED FOR CLARITY]">  </div>  <div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress="" style="width: 100%;"></span></div>  <div class="dz-success-mark"><span>✔</span></div>  <div class="dz-error-mark"><span>✘</span></div>  <div class="dz-error-message"><span data-dz-errormessage="">Invalid JSON response from server.</span></div></div>"outerText: "217140-112x56-Cricket-150x75.png↵3 KB✘"ownerDocument: documentparentElement: div#asset_upload.dropzone-wrap.clearfix.dz-clickable.dz-startedparentNode: div#asset_upload.dropzone-wrap.clearfix.dz-clickable.dz-startedprefix: nullpreviousElementSibling: div.dz-link-wrap.clearfix.fback-dzpreviousSibling: textscrollHeight: 144scrollLeft: 0scrollTop: 0scrollWidth: 132shadowRoot: nullspellcheck: truestyle: CSSStyleDeclarationtabIndex: -1tagName: "DIV"textContent: "      217140-112x56-Cricket-150x75.png    3 KB          ✔  ✘  Invalid JSON response from server."title: ""translate: truewebkitdropzone: ""__proto__: HTMLDivElementpreviewTemplate: div.dz-preview.dz-processing.dz-image-preview.dz-errorprocessing: truesize: 2994status: "error"type: "image/png"upload: ObjectwebkitRelativePath: ""width: 112xhr: XMLHttpRequest__proto__: File Invalid JSON response from server.

**Comment by robcarey** [comment]
Perhaps related.  I have tried completely uninstalling the extra and removing the lib directory, and then re installing.

I have noticed, that immediately after this - before attempting any asset adding of any kind, going into the Asset Manager under the Extras menu generates some modX errors.

First: accessing the Library tab generated the following ModX errors in the log - but no visual errors are apparent on the Library tab interface:

[2015-03-04 10:32:32] (ERROR @ /home/xxx/domains/xxx.xxx.com/modx/core/components/assman/model/assman/asset.class.php : 678) PHP warning: Invalid argument supplied for foreach()
[2015-03-04 10:32:32] (ERROR @ /home/xxx/domains/xxx.xxx.com/modx/core/components/assman/model/assman/asset.class.php : 678) PHP warning: Invalid argument supplied for foreach()

Next - clicking the "Verify" button on the verify tab generates the following modX error message in the log:

 [2015-03-04 10:34:11] (ERROR in Asset::verifyFiles @ 929) Asset does not exist: /home/xxx/domains/xxx.xxx.com/public_html/assets/lib/

This also generates a blank manager page for the tab.  The stadar ModX manager tree and topbar are visible, however the content area on the right is completely empty.  No feedback to the user on whether the verify command worked or not and no way to navigate the other asset manager tabs that were previously visible.

I also tried to run a verify after uploading a single asset image (which generates the original issues outlined previously) - the blank page is the same - no info returned, however ModX did not generate the previous issue.  I assume it's because the lib directory now exists after uploading an asset.  However... there's still no way to know if anything occured during the verify operation...

**Comment by fireproofsocks** [comment]
Can you give me access to this installation to debug this?

**Comment by robcarey** [comment]
One final addendum.  After the exercise above - adding a single asset from the asset tab on a resource - I have verified that 

1. the file is uploading correctly
2. a record of the file is stored in "ass_assets" table
3. NO record is creates in "ass_page_assets" table

Sadly - I cannot give you access for logistical reasons.  This is on a VM behind a corporate firewall :(

I wish I could.  This seems like a confusing one.

**Comment by fireproofsocks** [comment]
Bummer.  I think this is in part an environment issue, which are nearly impossible to debug, so I'm not confident I can reproduce and fix this.

Did the assets/lib/ directory get created?

**Comment by robcarey** [comment]
Yes.  The lib directory is created on demand - as are all child folders.

**Comment by fireproofsocks** [comment]
What's the file and line number for the PHP warning?

**Comment by robcarey** [comment]
Arg.  I purged the log to give you a clean view in case we skyped.  And I needed to hide some company IPs and such.  Now I'm not getting that error any more even when duplicating the steps.

I think we're out of options here, but for background, this is a new VM running a VirtualMin setup.  Just set up a few days ago running the Ubuntu setup outlined above.  

For curiosity's sake, I just created a new virtual host and did a completely fresh install of modx on the new site.  Once installed I logged in and installed the Asset Manager extra so that there were no other possible collisions.  Same issues as outlined above.

I agree it's an environment issue for sure - but this is a pretty standard setup.  I tried making the entire site structure fully writable to rule out any file permissions issues with no success.  Of course that's not practical - just troubleshooting :)

One possible thing - I am running modX advanced, with the modx core being kept below the site root.  This is pretty common though as it's a suggested method of hardening modx security.  But I mention it in case it helps.

Are there any apache modules or php configs that are required (beyond ImageMagick) that I may be missing?

Thanks

**Comment by fireproofsocks** [comment]
Ok, thanks for the info.  I'll try to reproduce the issue, but I'm not holding my breath.   If there are any missing modules, the php logs should be screaming about them.

**Comment by fireproofsocks** [comment]
Do you want to try moving the MODX core into the standard location and see if that makes a difference?

Also, does installing the package via Repoman make any difference?  

I've just tried installing via package manager and via repoman and I cannot reproduce the problems you've described.

**Comment by robcarey** [comment]
I'm not familiar with repoman - I'll have to review it.  I will try a new modx standard install now.

**Comment by robcarey** [comment]
ok - same issues with a modx standard installation and I got the php error numbers now :)

These were generated on a completely fresh install - first package, no mods.  Hope it helps!

[2015-03-04 12:57:44] (ERROR @ /home/xxxx/public_html/core/components/assman/model/assman/asset.class.php : 678) PHP warning: Invalid argument supplied for foreach()
[2015-03-04 12:57:44] (ERROR @ /home/xxxx/public_html/core/components/assman/model/assman/asset.class.php : 678) PHP warning: Invalid argument supplied for foreach()

**Comment by robcarey** [comment]
I can't seem to make heads or tails out of repoman unfortunately.  Might be above my pay grade ;)

**Comment by fireproofsocks** [comment]
Repoman allows you to develop MODX packages in a sane and reusable way, and importantly, in this case it would allow you to install the very latest code without using the MODX package manager.

**Comment by fireproofsocks** [comment]
Final thing to try: download the latest manual build from https://github.com/craftsmancoding/assetmanager/tree/master/builds

and install that (you have tell the MODX package manager to search locally).

Other than that, there's not much I can do here to troubleshoot an issue that seems particular to your environment.

**Comment by robcarey** [comment]
Well I got it installed via repoman (thanks to the helpful repoman demo video)

However the issues persist.  I'm at a loss.... hopefully someone finds out.  Thanks for your help.

**Comment by fireproofsocks** [comment]
It is exceedingly improbably that anybody but a developer with access to your particular system will be able to sort this out because it appears to be an environment issue.  There's a possibility that future fixes accidentally bypass the condition that is causing the problems, but that's not a good way to do development.  If you've got a vagrant file or some other way for me to reproduce the environment, then I can troubleshoot further, otherwise it's essentially a lost cause.  Try installing it elsewhere would be obvious suggestion here.

**Comment by robcarey** [comment]
SONOFABITCH. :)  Issue resolved!

Somehow GD was not installed on this config.  Installed GD and the problem is gone!  

Might be a good add to the list of requirements!  Thanks for your patience on this!

Rob

**Comment by fireproofsocks** [comment]
WOW.  Well done.  I will absolutely add a check for this a la http://www.zoopable.com/check-php-gd-library-installed-or-not/
