### ISSUE TITLE
Assigning getPageAssets only to a specific resource

### ISSUE THREAD

**Issue by deyand** [craftsmancoding/assetmanager#55]
Hi,
is there a way to show the Assets tab only in specific resource/template? I don't want to be shown on every page.
I'm using MODX 2.3.3 and PHP 5.4

**Comment by dadaniels** [comment]
This feature has now been added on the next release.
On the system settings, assman.skip_templates has been added. You can enter a comma separated ids of the template that you dont want an Asset tab to appear.

**Comment by deyand** [comment]
I'm using it right now with MODX 2.4 and Asset manager 1.1.1 also tried it on 2.3.3 and in both cases there is no such feature in system settings under assman or wherever.
