### ISSUE TITLE
Standard styles in the manager-panel is displayed incorrectly

### ISSUE THREAD

**Issue by Ruslan-Aleev** [craftsmancoding/assetmanager#56]
1) The component's styles is connected below the standard styles and use the id or class of the standard styles manager-panel, and because of this, some styles in the manager-panel is displayed incorrectly.
Also better to use an already plugged-in manager-panel fontawesome icons instead of images.

2) All links in the "Assets"-tab (Report a Bug | Wiki | Get Support and others) it is more logical to do with the attribute target="_blank"

Version MODX Revolution 2.3.3-pl (traditional)

**Comment by dadaniels** [comment]
We just pushed an updates on the repo and these updates will be carried out on the next release of the plugin.

But to make certain can you show me a screenshot of the broken style of the modx manager clashing with assetmanager css? we already fixed this issue on other tickets we just want to make sure that what you;re seeing is the same as the other ticket.

thank you for suggesting the usage of fontawesome, we already update the trash icon to use font awesome asset and we also added a target new tab on footer links.

**Comment by Ruslan-Aleev** [comment]
Thanks for the info. We will wait for new version =)
Here is manager panel with the Assets Manager and without:
![with_1](https://cloud.githubusercontent.com/assets/12523676/7742217/fcf214fe-ff94-11e4-959c-e7d36017cdd8.png)
![with_2](https://cloud.githubusercontent.com/assets/12523676/7742222/05af7140-ff95-11e4-829f-f03a638bf003.png)
![with_3](https://cloud.githubusercontent.com/assets/12523676/7742223/0a0d0504-ff95-11e4-92fc-29b24b8b49f8.png)
![without_1](https://cloud.githubusercontent.com/assets/12523676/7742224/0db980b0-ff95-11e4-940e-81242aad9b99.png)
![without_2](https://cloud.githubusercontent.com/assets/12523676/7742226/109b4a16-ff95-11e4-90a5-67602c052cf8.png)

**Comment by dadaniels** [comment]
those layout problems were already fixed on other issues. please wait for the next release. thank you
