### ISSUE TITLE
Problem to upload for Users

### ISSUE THREAD

**Issue by gravino81** [craftsmancoding/assetmanager#57]
Hello
I encountered this problem and I hope someone can help me.

Users who do not have "Sudo User" can not upload photos and receive this error: "Something went wrong. Please check the Asset Manager Setting Page and See if the image meet the max upload size"

I think the message is random because the limit is not exceeded and with the admin user can upload this photo without the problems. 

I tried to change all the parameters at users but only if checked "Sudo User" can upload.

**Comment by fireproofsocks** [comment]
What version of the plugin and what version of MODX are you using, please.

**Comment by gravino81** [comment]
Hello 

MODX Revolution 2.3.3-pl
Asset Manager 1.1.1-pl

Thanks!

**Comment by dadaniels** [comment]
I dont experience this on the updated version form this repo, I tried to create a new user group with a limited access on the manager non sudo user as well, I can still upload an image. I also tried to uncheck Sudo User on my admin and it still works.

**Comment by gravino81** [comment]
I reinstalled the component and solved the problem!
