### ISSUE TITLE
Build Script?

### ISSUE THREAD

**Issue by jpdevries** [craftsmancoding/assetmanager#62]
Is there a build script in the repository that can be used to build the transport package?

**Comment by fireproofsocks** [comment]
No: that's the entire raison d'etre of Repoman: https://github.com/craftsmancoding/repoman

Build scripts are a huge pain, massively confusing, an insurmountable roadblock to MODX noobs, and entirely unnecessary (imo).  So all my projects follow a consistent and orderly project structure (compatible with Repoman) and are built using the Repoman utilty: `php repoman build path/to/repo` and nobody needs to waste time reinventing square wheels or performing self-flagellation.

Is there something in particular you wanted a build script for?

**Comment by jpdevries** [comment]
I was looking for a way to build the project after forking it (in case the JS fix isn't merged)



—

**Comment by fireproofsocks** [comment]
Use Repoman to build.  It's for exactly this type of case.

**Comment by jpdevries** [comment]
Cool. I'll try Repoman out. Maybe worth adding a note about repo man in a CONTRIBUTING.MD or something?




—
