### ISSUE TITLE
Big picture with  data-src - not working!!!  

### ISSUE THREAD

**Issue by ufabooks** [craftsmancoding/assetmanager#71]
< figure class="one-fourth" data-src="[[+Asset.url]]" >
< img src="[[+asset_id:resize=`800x600`]]" width="[[+asset_id.width]]" height="600">  
< /figure>

 data-src="[[+Asset.url]]" - does not display a picture

**Comment by fireproofsocks** [comment]
This isn't enough info to reproduce the issue.  Is the code same in a Template or a Chunk?  Is a Snippet called and how?

**Comment by ufabooks** [comment]
Snippet [[ getPageAssets?      &innerTpl=`innerass`    &is_image=`1`]] 
chank  innerTpl  

< figure class="one-fourth" data-src="[[+Asset.url]]" >
< img src="[[+asset_id:resize=800x600]]" width="[[+asset_id.width]]" height="600">
< /figure>

**Comment by fireproofsocks** [comment]
If I'm understanding this correctly, returning base64 encoded image data was never built as part of the functionality.
