### ISSUE TITLE
Two asset manager on two sites with one database

### ISSUE THREAD

**Issue by ufabooks** [craftsmancoding/assetmanager#74]
Your module appears creates tables in base. And if I establish one more asset manager on the hosting on other site (and a database one on all sites), there is a breakage of both galleries on both sites. What to do?

**Comment by fireproofsocks** [comment]
I can't remember if there is a prefix on the table names that's configurable somewhere, but really, the best option is to find a host that provides you multiple databases.

**Comment by ufabooks** [comment]
I didn't find a configuration with a prefix anywhere. And very much it would be necessary

**Comment by fireproofsocks** [comment]
Unfortunately, it's not possible -- much better to use separate databases.  You can hack the `model/migrations/install.php` script to modify the prefix used, but that's not recommended.
