### ISSUE TITLE
Unable to create group

### ISSUE THREAD

**Issue by JuliaPhoenix** [craftsmancoding/assetmanager#75]
Hello,
Version Modx Revo 2.4.2. Version assetmanager-1.1.1-pl. Php 5.4. When you try to create a group that's open this page http://joxi.ru/vAW3Xv8ukVkg1A. Redirects to the home page, but the page is a broken and without style. I guess that's incompatible versions. Or I'm wrong and this error can be eliminated?

**Comment by chrisdempsey** [comment]
I experience the same issue in 2.4.3 with 1.1.1 on php 5.5.

**Comment by ufabooks** [comment]
I experience the same issue

**Comment by fireproofsocks** [comment]
Not re-produceable in upcoming release; presumed fixed.
