### ISSUE TITLE
Link under extras broke manager

### ISSUE THREAD

**Issue by ysanmiguel** [craftsmancoding/assetmanager#81]
Hello I just install the Assets manager 1.1.1-pl on ModX Revo 2.5.0-pl and realise that the link under Extras (top Menu) takes me to url.com/manager/?a=9 but all the page looks like has not CSS, just white page full of manager links.

just to report that, not sure if is only me. Thank you!

**Comment by ysanmiguel** [comment]
Move post to: https://github.com/craftsmancoding/assetmanager/issues/78

**Comment by hitodev** [comment]
same problem
