### ISSUE TITLE
Mysql strict mod

### ISSUE THREAD

**Issue by Monggi68** [craftsmancoding/assetmanager#83]
AssetManager can not be installed with mysql strict mod enabled.
In Mysql 5.7 strict mod will be no possibility to disable it. Any solution for that ?

**Comment by Mark-H** [comment]
This is still a problem. There are a number of columns that are set to `null="false"`, without a default, that is preventing assets from being saved to the database.

**Comment by fireproofsocks** [comment]
I can reproduce this in Docker.  Stay tuned...

**Comment by fireproofsocks** [comment]
The only solution is to comb through the code and set viable default values for database insertion operations.  Version 1.3.1 should have those in place.  The code is on the master branch.
